theme: jekyll-theme-minimal
title: [Valentin Kononov public profile and CV]
description: [Full-Stack software developer, interested in web development using TypeScript, Backend development with NodeJS, NestJS, .NET Core, open for the new skills]
logo: [Valentin_2019.png]
show_downloads: ["true"]