theme: jekyll-theme-minimal
title: Valentin Kononov public profile and CV
description: Senior Backend Software Engineer, interested API development, databases and infrastructure
logo: /assets/Valentin_2024.jpg